
-- Compañera Financiera V11 - Supabase schema
-- Pegá TODO este archivo en Supabase > SQL Editor > New query > Run.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  name text,
  gastos_vivir numeric default 0,
  meta_emergencia numeric default 0,
  fondo_actual numeric default 0,
  sueldo numeric default 0,
  extras numeric default 0,
  extraordinarios numeric default 0,
  created_at timestamptz default now()
);

create table if not exists public.debts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  entity text,
  saldo numeric default 0,
  saldo_inicial numeric default 0,
  cuota numeric default 0,
  cuotas_restantes integer default 0,
  cft numeric default 0,
  oferta numeric default 0,
  estado text default 'Activa',
  created_at timestamptz default now()
);

create table if not exists public.recurrents (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text,
  importe numeric default 0,
  frecuencia text,
  activo boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.people (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text,
  tipo text,
  saldo numeric default 0,
  saldo_inicial numeric default 0,
  estado text default 'Activa',
  created_at timestamptz default now()
);

create table if not exists public.snapshots (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  fecha date not null default current_date,
  deuda_total numeric default 0,
  fondo numeric default 0,
  created_at timestamptz default now()
);

alter table public.profiles enable row level security;
alter table public.debts enable row level security;
alter table public.recurrents enable row level security;
alter table public.people enable row level security;
alter table public.snapshots enable row level security;

drop policy if exists "profiles_own" on public.profiles;
create policy "profiles_own" on public.profiles for all
using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "debts_own" on public.debts;
create policy "debts_own" on public.debts for all
using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "recurrents_own" on public.recurrents;
create policy "recurrents_own" on public.recurrents for all
using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "people_own" on public.people;
create policy "people_own" on public.people for all
using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "snapshots_own" on public.snapshots;
create policy "snapshots_own" on public.snapshots for all
using (auth.uid() = user_id) with check (auth.uid() = user_id);
